# We're assuming that MySQL is the database in use. If not, please change the value of adapter to match your database
# setup, after editing the Gemfile. For example, SQLite3 uses the 'sqlite3' adapter, and PostgreSQL uses the
# 'postgresql' adapter.
production:
  adapter: mysql2
  database: <%= ENV['COURIER_DATABASE_NAME'] %>
  host: <%= ENV['COURIER_DATABASE_HOST'] %>
  username: <%= ENV['COURIER_DATABASE_USERNAME'] %>
  password: <%= ENV['COURIER_DATABASE_PASSWORD'] %>
  reconnect: true

#development:
#  adapter: mysql2
#  database: <%= ENV['COURIER_DATABASE_NAME'] %>
#  host: <%= ENV['COURIER_DATABASE_HOST'] %>
#  username: <%= ENV['COURIER_DATABASE_USERNAME'] %>
#  password: <%= ENV['COURIER_DATABASE_PASSWORD'] %>
#  reconnect: true
#
#test:
#  adapter: mysql2
#  database: <%= ENV['COURIER_DATABASE_NAME'] %>
#  host: <%= ENV['COURIER_DATABASE_HOST'] %>
#  username: <%= ENV['COURIER_DATABASE_USERNAME'] %>
#  password: <%= ENV['COURIER_DATABASE_PASSWORD'] %>
#  reconnect: true
